name: 'Download OpenJDK'
description: 'Download OpenJDK from https://jdk.java.net'
inputs:
  feature:
    description: 'Feature number of the JDK to download'
    required: true
    default: '14'
outputs:
  file:
    description: 'The path to the downloaded file'
  version:
    description: 'The feature version of the downloaded OpenJDK'
runs:
  using: 'node12'
  main: 'dist/index.js'
