name: 'Download OpenJDK'
description: 'Download OpenJDK from https://jdk.java.net'
inputs:
  feature:
    description: 'Feature number of the JDK to download'
    required: true
    default: '14'
outputs:
  jdk-file:
    description: 'The path to the downloaded file'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.feature }}
